name: cavil
version: 0.1.0.0
synopsis: Recorded, randomised decisions
description: See README at <https://github.com/eddiejessup/cavil#readme>
maintainer: Elliot Marsden <elliot.marsden@gmail.com>
github: eddiejessup/cavil

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-warnings-deprecations
- -Wno-incomplete-patterns
- -Wno-incomplete-uni-patterns
- -Wmissing-deriving-strategies

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - containers
  - cryptohash-sha256
  - data-default
  - generic-optics
  - githash
  - optics
  - optparse-applicative
  - postgresql-simple
  - protolude
  - safe
  - servant
  - servant-server
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - wai-cors
  - wai-extra
  - warp

library:
  source-dirs: src

executables:
  app:
    main: Main.hs
    source-dirs: app
    dependencies:
      - cavil

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - cavil
      - Cabal
      - tasty
      - tasty-hunit

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
