name: cavil
version: 0.1.0.2
synopsis: Recorded, randomised decisions
description: See README at <https://github.com/eddiejessup/cavil#readme>
maintainer: Elliot Marsden <elliot.marsden@gmail.com>
github: eddiejessup/cavil

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wno-incomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Widentities
  - -Wpartial-fields
  - -haddock

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - cabal-file-th
  - containers >= 0.6.4 && < 0.6.5
  - cryptohash-sha256
  - data-default
  - generic-optics
  - optics
  - optparse-applicative
  - postgresql-simple
  - protolude
  - safe
  - servant
  - servant-server
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - wai-cors
  - wai-extra
  - warp

library:
  source-dirs: src

executables:
  app:
    main: Main.hs
    source-dirs: app
    dependencies:
      - cavil

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - cavil
      - Cabal
      - tasty
      - tasty-hunit

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
